service: muntants-consumer
runtime: java11
env: standard
instance_class: F2
handlers:
  - url: /.*
    script: auto
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic
  min_pending_latency: 1s
  max_pending_latency: automatic
network: {}
inbound_services:
  - warmup